export const ADD_NEW_WORD = 'ADD_NEW_WORD';

export const CREATE_TEST_START = 'CREATE_TEST_START';
export const CREATE_TEST_SUCCESS = 'CREATE_TEST_SUCCESS';

export const SELECT_ANSWER_SUCCESS = 'SELECT_ANSWER_SUCCESS';
export const SELECT_ANSWER_WRONG = 'SELECT_ANSWER_WRONG';

export const FINISH_TEST = 'FINISH_TEST';

export const SELECT_HISTORY_TEST = 'SELECT_HISTORY_TEST';
